### ISSUE TITLE
Rollup export missing esutils from dependencies

### ISSUE THREAD

**Issue by kevinkace** [tivac/modular-css#264]
```
ERR! cli Build failed!
ERR! cli { Error: Cannot find module 'esutils'
ERR! cli     at Function.Module._resolveFilename (module.js:455:15)
ERR! cli     at Function.Module._load (module.js:403:25)
ERR! cli     at Module.require (module.js:483:17)
ERR! cli     at require (internal/module.js:20:19)
ERR! cli     at Object.<anonymous> (***\Build\node_modules\modular-css-rollup\rollup.js:6:33)
ERR! cli     at Module._compile (module.js:556:32)
ERR! cli     at Object.Module._extensions..js (module.js:565:10)
ERR! cli     at Module.load (module.js:473:32)
ERR! cli     at tryModuleLoad (module.js:432:12)
ERR! cli     at Function.Module._load (module.js:424:3) code: 'MODULE_NOT_FOUND' }
```

**Comment by tivac** [comment]
This will go out in `modular-css-rolup@4.1.3` shortly. Everything <= `4.1.2` has been deprecated in NPM.
