### ISSUE TITLE
Default empty string for assetFileNames

### ISSUE THREAD

**Issue by kevinkace** [tivac/modular-css#447]
I'm upgrading from `modular-css/rollup`@8 to `modular-css-rollup`@12 and ran into an issue:

> TypeError: Path must be a string. Received undefined
at assertPath (path.js:28:11)
at Object.join (path.js:489:7)
at Object.generateBundle (D:\thing\build\node_modules\modular-css-rollup\rollup.js:100:27)

Is a fallback needed [rollup.js line 102](https://github.com/tivac/modular-css/blob/master/packages/rollup/rollup.js#L102), similar to [line 98](https://github.com/tivac/modular-css/blob/master/packages/rollup/rollup.js#L98)?

**Comment by tivac** [comment]
This is fixed in `modular-css-rollup@13.0.0`
