### ISSUE TITLE
modular-css-svelte explodes on empty CSS files

### ISSUE THREAD

**Issue by tivac** [tivac/modular-css#512]
```
[!] (svelte plugin) TypeError: Cannot read property 'join' of undefined
menu\pages\play\components\character-portrait.html
TypeError: Cannot read property 'join' of undefined
    at content.replace.replace (~~~node_modules\modular-css-svelte\src\markup.js:25:72)
    at String.replace (<anonymous>)
    at updateCss (~~~node_modules\modular-css-svelte\src\markup.js:23:10)
    at extractLink (~~~node_modules\modular-css-svelte\src\markup.js:87:12)
    at <anonymous>
```

https://github.com/tivac/modular-css/blob/6e5d2b66d94247b602f0e277508f4f51faf8db34/packages/svelte/src/markup.js#L25

Looks like it isn't checking to be sure that `exported[key]` exists before trying to `.join()` it, not currently sure how it's even matching given that `exported` should be empty.

**Comment by tivac** [comment]
Turns out it generates a nonsense regex!

`(\b)css\.()(\b)` matches all sorts of things, but always calls the callback w/ an empty `key` param so of course looking that up doesn't go anywhere helpful.
