### ISSUE TITLE
File is walked but then later removed and never re-walked (Svelte)?

### ISSUE THREAD

**Issue by stffrd** [tivac/modular-css#522]
I'm currently running into an issue in `@modular-css/svelte` where a file of mine is being walked, but then removed due to having been seen in the processor in `svelte/src/markup.js`. It looks like the processor already contains my file, and as a result, the file (and its dependencies) are `removed` from the processor files cache. 

Here's the code that gives me a problem:

```
 // Remove any files that've already been encountered, they should be re-processed
    if(external in processor.files) {
        [ ...processor.dependents(external), external ].forEach((file) => processor.remove(file));
    }
```

... At what point do the files get re-processed? because it looks to me like each file is walked once, its dependencies all inspected on its walking, and then THAT'S IT. This looks like code that just nixes a file entirely if nothing else references it as a dependency?

My file situation is as follows:

- we'll call the file this problem is occuring in `file A`
- `file A` has a _single_ `:external` selector reference to `file B`
- `file B` has _several_ `:external` selector references to a third, more shared file, `file C`

This doesn't seem too weird to me here, but I thought it was useful to include what the dep graph might look like. 

In my various debugging attempts, I did a lot of in-module `console` logging. 

- I'm able to see `file A` get processed
- Since `file B` is a dependency, I see `file B` get processed. 
- At some point, the code above in `markup.js` is hit, and the processor contains `file A`, so `file A` and its dependency `file B` are removed
- Later on, `file B` is walked and included in the processor again (probably just as a top level glob walk)
- `file A` is never added to the processor again and never makes it to the output. 
- I receive a `Node does not exist` error. 

Here's a stacktrace:

```
[!] (@modular-css/rollup plugin) Error: Node does not exist: ...\a.css
Error: Node does not exist: ...\a.css
    at DepGraph.dependenciesOf (...\node_modules\dependency-graph\lib\dep_graph.js:187:13)
    at Processor.dependencies (...\node_modules\@modular-css\processor\processor.js:204:32)
    at css.forEach (...\node_modules\@modular-css\rollup\rollup.js:150:38)
    at Array.forEach (<anonymous>)
    at Object.entries.forEach (...\node_modules\@modular-css\rollup\rollup.js:148:21)
    at Array.forEach (<anonymous>)
    at Object.generateBundle (...\node_modules\@modular-css\rollup\rollup.js:136:37)
    at ...\node_modules\rollup\dist\rollup.js:20853:25
    at <anonymous>
```

If I comment out the removal code, this error goes away and things seem to work as intended, but I'm not 100% sure what the side effects are of eliminating that chunk of code happen to be. 

Let me know if you need any more information!

**Comment by tivac** [comment]
That functionality was added in #463 as a fix for #462 , but I have no further information about where the need for this came from.

I think a better approach would be to *not* remove files by default, and instead only remove them if you pass a `clean` option or something. Seems like it would let both use-cases coexist peacefully w/o bothering each other?
