### ISSUE TITLE
rollup-rewriter doesn't handle unknown deps well

### ISSUE THREAD

**Issue by tivac** [tivac/modular-css#688]
## Expected Behavior
When dealing with unknown dependencies, `@modular-css/rollup-rewriter` should cleanly handle them without exploding.

## Current Behavior

🔥

```
(!) Unresolved dependencies
https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
@sveltejs/svelte-virtual-list (imported by thing.svelte)
[!] (plugin @modular-css/rollup-rewriter) TypeError: Cannot destructure property `assets` of 'undefined' or 'null'.
TypeError: Cannot destructure property `assets` of 'undefined' or 'null'.
    at css.reduce (c:\project\node_modules\@modular-css\rollup-rewriter\rewriter.js:100:55)
    at Array.reduce (<anonymous>)
    at entries.forEach (c:\project\node_modules\@modular-css\rollup-rewriter\rewriter.js:99:23)
    at Map.forEach (<anonymous>)
    at Object.generateBundle (c:\project\node_modules\@modular-css\rollup-rewriter\rewriter.js:68:21)
    at Promise.resolve.then (c:\project\node_modules\rollup\dist\rollup.js:16621:25)
```

Error is coming from this chunk of code

https://github.com/tivac/modular-css/blob/0e913b002823711ee34017e60c4f5c323b190782/packages/rollup-rewriter/rewriter.js#L103-L109

## Possible Solution

A conditional early-out before the destructuring would solve that.

```diff
const css = [
    ...graph.dependenciesOf(file),
    ...(file in chunks ? chunks[file].imports : []),
    file,
].reduce((out, curr) => {
+   if(!chunks[curr]) {
+       return out;
+   }
+
    const { assets = [] } = chunks[curr];

    assets.forEach((asset) => out.add(asset));

    return out;
}, new Set());
```

**Comment by tivac** [comment]
This is released in `@modular-css/rollup-rewriter@25.6.0`
